package rudeauth

import (
	"bytes"
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// katVectors is the subset of testdata/vectors.json the SDK's crypto must
// reproduce. The file is generated by the server's own cmd/rudeauth-vectors, so
// matching it proves the SDK agrees with the server, not merely with itself.
type katVectors struct {
	Ed25519 struct {
		PublicKey string `json:"public_key_hex"`
		Endpoint  string `json:"endpoint"`
		Data      string `json:"data_hex"`
		Signature string `json:"signature_hex"`
	} `json:"ed25519"`
	X25519 struct {
		PrivateA string `json:"private_a_hex"`
		PublicB  string `json:"public_b_hex"`
	} `json:"x25519"`
	SessionKey struct {
		SessionID string `json:"session_id"`
		Key       string `json:"key_hex"`
	} `json:"session_key"`
	XChaCha struct {
		Key       string `json:"key_hex"`
		AAD       string `json:"aad"`
		Plaintext string `json:"plaintext_hex"`
		Sealed    string `json:"sealed_hex"`
	} `json:"xchacha20poly1305"`
}

func loadKAT(t *testing.T) katVectors {
	t.Helper()
	b, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var k katVectors
	if err := json.Unmarshal(b, &k); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	return k
}

func unhex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex %q: %v", s, err)
	}
	return b
}

// verify must accept a signature the server actually produced, over the exact
// domain-separated message, and reject tampering or a wrong endpoint.
func TestVerifyMatchesServerSignature(t *testing.T) {
	k := loadKAT(t)
	pub := ed25519.PublicKey(unhex(t, k.Ed25519.PublicKey))
	data := unhex(t, k.Ed25519.Data)
	sig := unhex(t, k.Ed25519.Signature)

	if !verify(pub, k.Ed25519.Endpoint, data, sig) {
		t.Fatal("rejected a signature the server actually produced")
	}
	tampered := append([]byte(nil), data...)
	tampered[0] ^= 0x01
	if verify(pub, k.Ed25519.Endpoint, tampered, sig) {
		t.Fatal("accepted a signature over tampered data")
	}
	if verify(pub, "variables", data, sig) {
		t.Fatal("accepted a signature bound to a different endpoint")
	}
}

// deriveSessionKey must reproduce the server's HKDF output exactly, or every
// sealed payload would fail to open.
func TestDeriveSessionKeyMatchesServer(t *testing.T) {
	k := loadKAT(t)
	got, err := deriveSessionKey(unhex(t, k.X25519.PrivateA), unhex(t, k.X25519.PublicB), k.SessionKey.SessionID)
	if err != nil {
		t.Fatalf("derive: %v", err)
	}
	if want := unhex(t, k.SessionKey.Key); !bytes.Equal(got, want) {
		t.Fatalf("session key = %x, want %x", got, want)
	}
}

// openSealed must open what the server sealed, and refuse the wrong AAD.
func TestOpenSealedMatchesServer(t *testing.T) {
	k := loadKAT(t)
	key := unhex(t, k.XChaCha.Key)
	sealed := unhex(t, k.XChaCha.Sealed)

	got, err := openSealed(key, sealed, []byte(k.XChaCha.AAD))
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if want := unhex(t, k.XChaCha.Plaintext); !bytes.Equal(got, want) {
		t.Fatalf("plaintext = %x, want %x", got, want)
	}
	if _, err := openSealed(key, sealed, []byte("files:core.dll")); err == nil {
		t.Fatal("opened with the wrong AAD")
	}
}
